from django.db import models

# Create your models here.
class DailyData(models.Model):

    date = models.DateField()
    last_modified = models.DateTimeField()
    USD = models.CharField(max_length=20)
    JPY = models.CharField(max_length=20)
    BGN = models.CharField(max_length=20)
    CZK = models.CharField(max_length=20)
    DKK = models.CharField(max_length=20)
    GBP = models.CharField(max_length=20)
    HUF = models.CharField(max_length=20)
    PLN = models.CharField(max_length=20)
    RON = models.CharField(max_length=20)
    SEK = models.CharField(max_length=20)
    CHF = models.CharField(max_length=20)
    ISK = models.CharField(max_length=20)
    NOK = models.CharField(max_length=20)
    HRK = models.CharField(max_length=20)
    RUB = models.CharField(max_length=20)
    TRY = models.CharField(max_length=20)
    AUD = models.CharField(max_length=20)
    BRL = models.CharField(max_length=20)
    CAD = models.CharField(max_length=20)
    CNY = models.CharField(max_length=20)
    HKD = models.CharField(max_length=20)
    IDR = models.CharField(max_length=20)
    ILS = models.CharField(max_length=20)
    INR = models.CharField(max_length=20)
    KRW = models.CharField(max_length=20)
    MXN = models.CharField(max_length=20)
    MYR = models.CharField(max_length=20)
    NZD = models.CharField(max_length=20)
    PHP = models.CharField(max_length=20)
    SGD = models.CharField(max_length=20)
    THB = models.CharField(max_length=20)
    ZAR = models.CharField(max_length=20)

    def __str__(self):
        return f"self.date: {self.date}"


class Hist90Data(models.Model):

    date = models.DateField()
    last_modified = models.DateTimeField()
    USD = models.CharField(max_length=20)
    JPY = models.CharField(max_length=20)
    BGN = models.CharField(max_length=20)
    CZK = models.CharField(max_length=20)
    DKK = models.CharField(max_length=20)
    GBP = models.CharField(max_length=20)
    HUF = models.CharField(max_length=20)
    PLN = models.CharField(max_length=20)
    RON = models.CharField(max_length=20)
    SEK = models.CharField(max_length=20)
    CHF = models.CharField(max_length=20)
    ISK = models.CharField(max_length=20)
    NOK = models.CharField(max_length=20)
    HRK = models.CharField(max_length=20)
    RUB = models.CharField(max_length=20)
    TRY = models.CharField(max_length=20)
    AUD = models.CharField(max_length=20)
    BRL = models.CharField(max_length=20)
    CAD = models.CharField(max_length=20)
    CNY = models.CharField(max_length=20)
    HKD = models.CharField(max_length=20)
    IDR = models.CharField(max_length=20)
    ILS = models.CharField(max_length=20)
    INR = models.CharField(max_length=20)
    KRW = models.CharField(max_length=20)
    MXN = models.CharField(max_length=20)
    MYR = models.CharField(max_length=20)
    NZD = models.CharField(max_length=20)
    PHP = models.CharField(max_length=20)
    SGD = models.CharField(max_length=20)
    THB = models.CharField(max_length=20)
    ZAR = models.CharField(max_length=20)

    def __str__(self):
        return f"self.date: {self.date}"


class HistData(models.Model):
    
    date = models.DateField()
    last_modified = models.DateTimeField()
    USD = models.CharField(max_length=20)
    JPY = models.CharField(max_length=20)
    BGN = models.CharField(max_length=20)
    CZK = models.CharField(max_length=20)
    DKK = models.CharField(max_length=20)
    GBP = models.CharField(max_length=20)
    HUF = models.CharField(max_length=20)
    PLN = models.CharField(max_length=20)
    RON = models.CharField(max_length=20)
    SEK = models.CharField(max_length=20)
    CHF = models.CharField(max_length=20)
    ISK = models.CharField(max_length=20)
    NOK = models.CharField(max_length=20)
    HRK = models.CharField(max_length=20)
    RUB = models.CharField(max_length=20)
    TRY = models.CharField(max_length=20)
    AUD = models.CharField(max_length=20)
    BRL = models.CharField(max_length=20)
    CAD = models.CharField(max_length=20)
    CNY = models.CharField(max_length=20)
    HKD = models.CharField(max_length=20)
    IDR = models.CharField(max_length=20)
    ILS = models.CharField(max_length=20)
    INR = models.CharField(max_length=20)
    KRW = models.CharField(max_length=20)
    MXN = models.CharField(max_length=20)
    MYR = models.CharField(max_length=20)
    NZD = models.CharField(max_length=20)
    PHP = models.CharField(max_length=20)
    SGD = models.CharField(max_length=20)
    THB = models.CharField(max_length=20)
    ZAR = models.CharField(max_length=20)

    def __str__(self):
        return f"self.date: {self.date}"